#!/bin/sh

# Set these paths appropriately

BIN=/Users/gueyeousseynou/Dropbox/dropbox_cs/treetagger/bin
CMD=/Users/gueyeousseynou/Dropbox/dropbox_cs/treetagger/cmd
LIB=/Users/gueyeousseynou/Dropbox/dropbox_cs/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
